#!/bin/sh
###################################################
#              SCREENSHOT SELECTED                #
###################################################
maim -i $(xdotool selectwindow) ~/Desktop/$(date +%F-%T).png --hidecursor