#!/bin/sh
## RELOAD THEME

## XRESOURCES
xrdb -load $HOME/.Xresources

## GTK
update-gtk

## CSS
update-css

## POLYBAR
update-mpd

## BSPWM
$HOME/.config/bspwm/bspwmrc

## WALLPAPER
xsetroot -mod 10 2 -bg "$(xrdb -query|awk '/^\*color0:/ {print $2}')" -fg "$(xrdb -query|awk '/^\*color8:/ {print $2}')"
