#!/bin/sh
## Reload Xresources
xrdb -load $HOME/.Xresources

## Reload Polybar
bar

## Update GTK
update-gtk

## Update CSS
update-css

## Reload Bspwm
$HOME/.config/bspwm/bspwmrc

## Update wallpaper
xsetroot -mod 10 2 -bg "$(xrdb -query|awk '/^\*color0:/ {print $2}')" -fg "$(xrdb -query|awk '/^\*color8:/ {print $2}')"
