#!/bin/bash
# CREATE GTK THEME BASED ON XRESOURCES

# (re)load in case we forgot
xrdb load ~/.Xresources

# create the directory if it doesn't exist 
dir=$HOME/.cache/tmp
if [ ! -d "{$dir}" ]; then
  mkdir -p ${dir}
fi

# grab colors from xrdb
tfile=$dir/curtemp
for i in {1...17}
do
  cur=$(xrdb -query all|egrep '(ground|color)'|cut -d '#' -f2)
  echo $cur >> $tfile
  curr=($(< $tfile))
done
#echo $tfile #test

# set up the colors from xrdb
BG="${curr[0]}"
FG="${curr[1]}"
BLK="${curr[2]}"
BBLK="${curr[3]}"
RED="${curr[4]}"
GRN="${curr[6]}"
YLW="${curr[8]}"
BLU="${curr[10]}"
MAG="${curr[12]}"
CYN="${curr[14]}"
WHT="${curr[16]}"

# gtkrc attributes; assign colors 
base_color=$BG
nbg_color=$BG
ntooltip_bg_color=$BG
nselected_bg_color=$WHT
ntext_color=$WHT
nfg_color=$FG
ntooltip_fg_color=$FG
nselected_fg_color=$BG
nmenubar_bg_color=$BG
nmenubar_fg_color=$WHT
ntoolbar_bg_color=$BG
ntoolbar_fg_color=$WHT
nmenu_bg_color=$BG
nmenu_fg_color=$FG
npanel_bg_color=$BG
npanel_fg_color=$WHT
nlink_color=$BLU

# theme directory 
# adjust as needed
themedir=$HOME/.themes

# grab currently selected theme
theme=$(cat $HOME/.gtkrc-2.0|grep "gtk-theme-name"|awk '{print}'|cut -d '=' -f2|awk '{gsub(/"/,"");print}')

# grab current theme colors
file=$themedir/$theme/gtk-2.0/gtkrc
tmpfile=$dir/coltemp

# take current gtk colors and place into an array;
# we will replace them with our current colors
for i in {1..17}
do
  gtkcol=$(cat $file|grep "_color:"|cut -d '\' -f$i|cut -d '#' -f2)
  echo $gtkcol >> $tmpfile
  arr=($(< $tmpfile))
done
# test
#echo ${arr[@]}

# action; set the new colors
sed -i "s/${arr[0]}/"$base_color"/;
        s/${arr[1]}/"$nbg_color"/;
        s/${arr[2]}/"$ntooltip_bg_color"/;
        s/${arr[3]}/"$nselected_bg_color"/;
        s/${arr[4]}/"$ntext_color"/;
        s/${arr[5]}/"$nfg_color"/;
        s/${arr[6]}/"$ntooltip_fg_color"/;
        s/${arr[7]}/"$nselected_fg_color"/;
        s/${arr[8]}/"$nmenubar_bg_color"/;
        s/${arr[9]}/"$nmenubar_fg_color"/;
        s/${arr[10]}/"$ntoolbar_bg_color"/;
        s/${arr[11]}/"$ntoolbar_fg_color"/;
        s/${arr[12]}/"$nmenu_bg_color"/;
        s/${arr[13]}/"$nmenu_fg_color"/;
        s/${arr[14]}/"$npanel_bg_color"/;
        s/${arr[15]}/"$npanel_fg_color"/;
        s/${arr[16]}/"$nlink_color'"'"/" $file

# remove temp color file
rm $tmpfile
rm $tfile
